# Generated by Django 2.1.1 on 2018-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
