# Generated by Django 2.2.4 on 2022-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nots',
            field=models.TextField(default='my node'),
        ),
    ]
