# Generated by Django 2.2.4 on 2022-09-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='jenin', max_length=255)),
                ('network', models.CharField(default='network1', max_length=255)),
                ('relateddate', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(default='new desription')),
            ],
        ),
    ]
